/**
 * Standalone seed script — populates the notes collection with sample data
 * so cursor pagination has something real to page through.
 *
 * Deliberately bypasses the full Nest bootstrap (no HTTP server, no DI
 * container) and talks to Mongoose directly, since a one-shot data script
 * has no need for the app's request-handling machinery. Run with
 * `pnpm run seed`.
 */
import 'dotenv/config';
import mongoose from 'mongoose';
import configuration from '../src/config/configuration';
import { Note, NoteSchema } from '../src/notes/schemas/note.schema';

/** How many sample notes to insert. */
const SEED_COUNT = 50;

const SAMPLE_TAGS = ['work', 'personal', 'ideas', 'todo', 'reading', 'recipes'];

/** Builds one fake note, spreading `createdAt` back over the last `SEED_COUNT` days so pages come back in a realistic, non-identical order. */
function buildNote(index: number): Partial<Note> {
  const daysAgo = SEED_COUNT - index;
  const createdAt = new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000);

  return {
    title: `Sample note #${index + 1}`,
    content: `This is the body of sample note #${index + 1}, generated by the seed script.`,
    tags: [SAMPLE_TAGS[index % SAMPLE_TAGS.length]],
    // Every 10th note starts archived, so `includeArchived` has something to filter.
    archived: index % 10 === 9,
    createdAt,
    updatedAt: createdAt,
  };
}

async function seed(): Promise<void> {
  const { mongodbUri } = configuration();

  await mongoose.connect(mongodbUri);

  console.log(`Connected to ${mongodbUri}`);

  const NoteModel = mongoose.model(Note.name, NoteSchema);

  // Start from a clean slate so re-running the script is idempotent instead
  // of accumulating duplicates on every run.
  await NoteModel.deleteMany({});

  const notes = Array.from({ length: SEED_COUNT }, (_, index) => buildNote(index));
  await NoteModel.insertMany(notes);

  console.log(`Seeded ${SEED_COUNT} notes.`);

  await mongoose.disconnect();
}

seed()
  .then(() => process.exit(0))
  .catch((error: unknown) => {
    console.error('Seeding failed:', error);
    process.exit(1);
  });
