name: notes-api
values:
  - key: host
    value: 'http://localhost:3000'
  - key: baseUrl
    value: 'http://localhost:3000/v1'
  - key: baseUrlV2
    value: 'http://localhost:3000/v2'
  - key: baseUrlV3
    value: 'http://localhost:3000/v3'
  - key: noteId
    value: ''
  - key: endCursor
    value: ''
  - key: startCursor
    value: ''
  - key: v2NextLink
    value: ''
  - key: v2PreviousLink
    value: ''
  - key: v3PreviousLink
    value: ''
  - key: v3LastLink
    value: ''
